stages:
  - validate
  - deploy
  - test

default:
  artifacts:
    when: always
    paths:
      - artifacts/
    expire_in: 30 days

validate-source-of-truth:
  stage: validate
  tags:
    - docker
  image: python:3.13-slim
  before_script:
    - python -m pip install --quiet PyYAML
  script:
    - python -m scripts.validate

deploy-vlans:
  stage: deploy
  tags:
    - network-deploy
  before_script:
    - source "$HOME/.venvs/ccnpauto/bin/activate"
    - python -m pip install --quiet --requirement requirements.txt
  resource_group: catalyst9000v
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - python -m scripts.deploy

verify-vlans:
  stage: test
  tags:
    - network-deploy
  before_script:
    - source "$HOME/.venvs/ccnpauto/bin/activate"
    - python -m pip install --quiet --requirement requirements.txt
  resource_group: catalyst9000v
  needs:
    - deploy-vlans
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - python -m scripts.test_deployment
