apiVersion: batch/v1
kind: Job
metadata:
  name: interface-collector
  namespace: network-automation
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: collector
          image: lab9-interface-collector:1.0
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: interface-collector-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
