all:
  hosts:
    iosxe_sandbox:
      ansible_host: REPLACE_WITH_RESERVED_IOSXE_HOST
      ansible_port: REPLACE_WITH_SSH_PORT
      ansible_network_os: cisco.ios.ios
      ansible_connection: ansible.netcommon.network_cli
