[agent]
  interval = "10s"
  flush_interval = "10s"
  hostname = "ccnpauto-workstation"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  report_active = true

[[inputs.mem]]

[[inputs.cisco_telemetry_mdt]]
  transport = "grpc"
  service_address = ":57000"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "$INFLUXDB_DB"
  skip_database_creation = true
  username = "$INFLUXDB_WRITE_USER"
  password = "$INFLUXDB_WRITE_USER_PASSWORD"
