[agent]
  interval = "10s"
  flush_interval = "10s"
  hostname = "ccnpauto-workstation"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  report_active = true

[[inputs.mem]]

[[inputs.cisco_telemetry_mdt]]
  transport = "grpc"
  service_address = ":57000"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"
