[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  hostname = "ccnpauto-workstation"
  omit_hostname = false

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  report_active = true

[[inputs.mem]]

[[inputs.cisco_telemetry_mdt]]
  transport = "grpc"
  service_address = ":57000"
  max_msg_size = 4000000
  source_field_name = "mdt_source"

  [inputs.cisco_telemetry_mdt.aliases]
    iosxe_cpu = "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization"
    iosxe_memory = "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic"
    iosxe_interface = "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"
